version: 2
updates:
  - package-ecosystem: npm
    directory: /p18n
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /p1e-auth
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /pie-gate
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /pie-users
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /pie-web
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: daily
