apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pieline
  name: pieline
spec:
  securityContext:
    allowPrivilegeEscalation: true
    capabilities: {}
    privileged: false
    readOnlyRootFilesystem: false
    seLinuxOptions: {}

  containers:
    - name: pie-gate
      image: localhost/pie-gate
      ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 1G
      env:
        - name: PORT
          value: "5000"
        - name: ADDR_AUTH
          value: localhost:5001
        - name: ADDR_USERS
          value: localhost:5002
        - name: ADDR_I18N
          value: localhost:5003

    - name: pie-auth
      image: localhost/pie-auth
      resources:
        limits:
          cpu: 100m
          memory: 1G
      env:
        - name: PORT
          value: "5001"
        - name: ADDR_USERS
          value: localhost:5002

    - name: pie-users
      image: localhost/pie-users
      resources:
        limits:
          cpu: 100m
          memory: 1G
      env:
        - name: PORT
          value: "5002"
        - name: DB_URL
          value: postgresql://users:users@localhost:5432/users
    - name: db-users
      image: postgres
      resources:
        limits:
          cpu: 100m
          memory: 500M
      volumeMounts:
        - name: mnt-users
          mountPath: /var/lib/postgresql/data
      env:
        - name: POSTGRES_USER
          value: users
        - name: POSTGRES_PASSWORD
          value: users

    - name: pi18n
      image: localhost/pi18n
      resources:
        limits:
          cpu: 100m
          memory: 1G
      env:
        - name: PORT
          value: "5003"

    - name: jaeger
      image: jaegertracing/all-in-one
      ports:
        - containerPort: 16686
          hostPort: 16686
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 1G

  volumes:
    - name: mnt-users
      hostPath:
          path: /home/vagrant/db/users
          type: DirectoryOrCreate
status: {}
