apiVersion: apps/v1
kind: Deployment
metadata:
  name: pie-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pie-web
  template:
    metadata:
      labels:
        app: pie-web
    spec:
      containers:
        - name: pie-web
          image: localhost:10000/pie-web
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: ADDR_GATE
              value: "http://pieline.gate.local"
---
apiVersion: v1
kind: Service
metadata:
  name: pie-web
spec:
  selector:
    app: pie-web
  ports:
    - port: 7000
