apiVersion: apps/v1
kind: Deployment
metadata:
  name: pie-gate
  labels:
    app: pie-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pie-gate
  template:
    metadata:
      labels:
        app: pie-gate
    spec:
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}

      containers:
        - name: pie-gate
          image: localhost/pie-gate
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 1G
          env:
            - name: PORT
              value: "5000"
            - name: ADDR_AUTH
              value: pie-auth-pod-0:5001
            - name: ADDR_USERS
              value: pie-users-pod-0:5002
            - name: ADDR_PROJECTS
              value: pie-proj-pod-0:5003
            - name: ADDR_I18N
              value: pi18n-pod-0:6000

status: {}
