name: Build JS
description: Build PieLine JavaScript service
inputs:
  working-directory:
    description: Build working directory
    required: true
runs:
  using: composite
  steps:
    - id: install
      run: yarn
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - id: build
      run: yarn build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
