name: Build Java
description: Build PieLine Java service
inputs:
  working-directory:
    description: Build working directory
    required: true
runs:
  using: composite
  steps:
    - id: build
      run: ./gradlew build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
