name: Bake OCI Image
description: Builds and publishes pieline service OCI image
inputs:
  token:
    description: Registry token
    required: true
  service:
    description: Service name
    required: true
  tag:
    description: Built image tag - defaults to SHA
    required: true
    default: ${{ github.sha }}
outputs:
  image:
    description: Published image name
    value: ${{ steps.make.outputs.name }}
runs:
  using: composite
  steps:
    - id: make
      run: |
        rawtag=${{ inputs.tag }}
        tag=${rawtag#refs/tags/}

        cd bake
        make ${{ inputs.service }} TAG=${tag} REGISTRY=ghcr.io/kkorolyov CREDS=${{ github.actor }}:${{ inputs.token }}
        echo "::set-output name=name::$(echo $${{ inputs.service }}:${tag})"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
