name: Bake OCI Image
description: Builds and publishes pieline service OCI image
inputs:
  token:
    description: Registry token
    required: true
  service:
    description: Service name
    required: true
  tag:
    description: Built image tag - defaults to SHA
    required: true
    default: ${{ github.sha }}
outputs:
  image:
    description: Published image name
    value: ${{ steps.tag.outputs.name }}
runs:
  using: composite
  steps:
    - id: bake
      run: |
        base=docker.pkg.github.com/${{ github.repository }}/${{ inputs.service }}

        rawtag=${{ inputs.tag }}
        tag=${rawtag#refs/tags/}

        name=${base}:${tag}

        bake/service/${{ inputs.service }}.sh -t $name
        echo "::set-output name=name::$(echo $name)"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - id: publish
      run: |
        echo ${{ inputs.token }} | buildah login -u ${{ github.actor }} --password-stdin https://docker.pkg.github.com
        buildah push ${{ steps.bake.outputs.name }}
      shell: bash
