name: Build Python
description: Build PieLine Python service
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 tox -r requirements.txt
      shell: bash

    - name: Lint
      run: flake8 src
      shell: bash

    - name: Protoc
      run: ./protoc.sh
      shell: bash

    - name: Tox
      run: tox
      shell: bash
