name: Build Python
description: Build PieLine Python service
inputs:
  working-directory:
    description: Build working directory
    required: true
runs:
  using: composite
  steps:
    - id: install
      run: |
        python -m pip install --upgrade pip
        pip install flake8 tox -r requirements.txt
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - id: lint
      run: flake8 src
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - id: protoc
      run: ./protoc.sh
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - id: tox
      run: tox
      working-directory: ${{ inputs.working-directory }}
      shell: bash
