apiVersion: apps/v1
kind: Deployment
metadata:
  name: pie-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pie-auth
  template:
    metadata:
      labels:
        app: pie-auth
    spec:
      containers:
        - name: pie-auth
          image: dreg.local/pie-auth
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          env:
            - name: PORT
              value: "5001"
            - name: DB_URL
              value: jdbc:h2:tcp://localhost:1521//opt/h2-data/auth
            - name: ADDR_USERS
              value: pie-users:5002
        - name: db-auth
          image: oscarfonts/h2
          volumeMounts:
            - name: pie-auth
              mountPath: /opt/h2-data
          env:
            - name: H2_OPTIONS
              value: -ifNotExists
      volumes:
        - name: pie-auth
          persistentVolumeClaim:
            claimName: pie-auth
---
apiVersion: v1
kind: Service
metadata:
  name: pie-auth
spec:
  selector:
    app: pie-auth
  ports:
    - port: 5001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pie-auth
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1G
