apiVersion: apps/v1
kind: Deployment
metadata:
  name: pie-gate
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pie-gate
  template:
    metadata:
      labels:
        app: pie-gate
    spec:
      containers:
        - name: pie-gate
          image: dreg.local/pie-gate
          env:
            - name: PORT
              value: "80"
            - name: ADDR_AUTH
              value: pie-auth
            - name: ADDR_USERS
              value: pie-users
            - name: ADDR_PROJECTS
              value: pie-proj
            - name: ADDR_I18N
              value: pi18n
---
apiVersion: v1
kind: Service
metadata:
  name: pie-gate
spec:
  selector:
    app: pie-gate
  ports:
    - port: 80
