name: Publish

on:
  push:
    tags: 
      - "[0-9].[0-9].[0-9]"

jobs:
  pi18n:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node ${{ matrix.version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.version }}

      - name: Publish image
        uses: ./.github/actions/bpub
        with:
          service: pi18n
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.ref }}

  pie-auth:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [1.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Java ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}

      - name: Publish image
        uses: ./.github/actions/bpub
        with:
          service: pie-auth
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.ref }}
  
  pie-proj:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [1.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Java ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}

      - name: Publish image
        uses: ./.github/actions/bpub
        with:
          service: pie-proj
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.ref }}

  pie-gate:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [1.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Java ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}

      - name: Publish image
        uses: ./.github/actions/bpub
        with:
          service: pie-gate
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.ref }}

  pie-users:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Publish image
        uses: ./.github/actions/bpub
        with:
          service: pie-users
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.ref }}

  pie-web:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node ${{ matrix.version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.version }}

      - name: Publish image
        uses: ./.github/actions/bpub
        with:
          service: pie-web
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.ref }}
