name: Verify

on: [push, pull_request]

jobs:
  pi18n:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.version }}
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        uses: ./.github/actions/build-js
        with:
          working-directory: pi18n

  pie-auth:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [1.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Java ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}

      - name: Build
        uses: ./.github/actions/build-java
        with:
          working-directory: pie-auth
          token: ${{ secrets.GITHUB_TOKEN }}

  pie-gate:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [1.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Java ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}

      - name: Build
        uses: ./.github/actions/build-java
        with:
          working-directory: pie-gate
          token: ${{ secrets.GITHUB_TOKEN }}

  pie-users:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Build
        uses: ./.github/actions/build-python
        with:
          working-directory: pie-users

  pie-web:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.version }}
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        uses: ./.github/actions/build-js
        with:
          working-directory: pie-web
